configuration :
    - name : alice
      ip   : 128.237.222.79 
      port : 12344
    
    - name : bob
      ip   : 128.237.222.79 
      port : 14255

    - name : charlie
      ip   : 128.2.13.145
      port : 12998

    - name : daphnie
      ip   : 128.2.13.145
      port : 1987

sendRules :
    - action : drop # Ack message number 4 from bob to alice will not be sent
      src    : bob
      dest   : daphnie
      kind   : Ack
    
    - action : delay # Every Lookup message in the system will be delayed
      kind   : Lookup
      
    - action : duplicate
      kind   : Ack
      src    : bob
      dest   : charlie
      
receiveRules :
    - action : drop # Ack message number 4 from bob to alice will not be sent
      src    : bob
      dest   : alice
      kind   : Ack
      seqNum : 4
      duplicate: true
    
    - action : delay # Every Lookup message in the system will be delayed
      kind   : Lookup
      dest   : daphnie
      
    - action : drop
      kind   : Ack
      src    : bob
      dest   : charlie
      duplicate: yes
